#!/usr/bin/env python3
"""Generate (or check) the ABI layout-freeze assertions for Liara.

For every public POD struct/union with a complete definition, emit
``static_assert`` checks on ``sizeof``, ``alignof`` and every field
``offsetof``. Opaque handles are forward-declared (incomplete) and are skipped
automatically.

The emitted header is committed as the golden reference and is compilable as
both C11 and C++. The layout-freeze CI step compiles it across the whole
compiler/OS matrix: if a struct's layout drifts, or differs between platforms,
a static_assert fails and the build goes red.

Two modes:

  (default)   write the golden header to --output.
  --check     regenerate in memory and compare to the committed --output;
              fail if they differ (a struct was added, removed, or changed
              without regenerating). This catches additions that pure
              compilation would not.

Usage::

    # regenerate after intentionally changing a struct
    python3 abi_layout_asserts.py --include-dir include \
        --output tests/abi/abi_layout.generated.h

    # CI completeness check
    python3 abi_layout_asserts.py --include-dir include \
        --output tests/abi/abi_layout.generated.h --check
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from clang import cindex


def builtin_include_args(compiler: str, extra: list[str]) -> list[str]:
    """Full system include search list from a compiler driver (clang or gcc)."""
    if extra:
        return [arg for path in extra for arg in ("-isystem", path)]
    resolved = shutil.which(compiler)
    if not resolved:
        return []
    try:
        proc = subprocess.run([resolved, "-E", "-x", "c++", "-v", os.devnull],
                              capture_output=True, text=True)
    except OSError:
        return []
    args: list[str] = []
    capture = False
    for line in proc.stderr.splitlines():
        stripped = line.strip()
        if stripped.startswith("#include <...> search starts here:"):
            capture = True
            continue
        if stripped.startswith("End of search list."):
            break
        if capture and stripped:
            path = stripped.split(" (")[0]
            if Path(path).is_dir():
                args += ["-isystem", path]
    return args


@dataclass
class Record:
    type_name: str          # C-usable name, e.g. "liara_transform_t" or "struct liara_x"
    size: int
    align: int
    fields: list[tuple[str, int]]   # (field name, byte offset)


def collect_records(index: cindex.Index, header: Path, include: str,
                    args: list[str]) -> list[Record]:
    tu = index.parse(str(header), args=args,
                     options=cindex.TranslationUnit.PARSE_SKIP_FUNCTION_BODIES)
    records: list[Record] = []
    header_resolved = header.resolve()
    for cursor in tu.cursor.walk_preorder():
        loc = cursor.location
        if not (loc.file and Path(loc.file.name).resolve() == header_resolved):
            continue
        if cursor.kind not in (cindex.CursorKind.STRUCT_DECL, cindex.CursorKind.UNION_DECL):
            continue
        if not cursor.is_definition() or cursor.is_anonymous():
            continue
        t = cursor.type
        size = t.get_size()
        if size <= 0:                       # incomplete / dependent
            continue
        fields: list[tuple[str, int]] = []
        for field in cursor.get_children():
            if field.kind != cindex.CursorKind.FIELD_DECL:
                continue
            if field.is_bitfield() or not field.spelling:
                continue                    # offsetof is not valid on bitfields
            fields.append((field.spelling, field.get_field_offsetof() // 8))
        records.append(Record(t.spelling, size, t.get_align(), fields))
    return records


def render(records: list[Record], includes: list[str]) -> str:
    lines = [
        "// AUTO-GENERATED by abi_layout_asserts.py -- do not edit by hand.",
        "// Regenerate after any intentional struct change and commit the result.",
        "#pragma once",
        "",
        "#include <assert.h>    // static_assert (C11)",
        "#include <stddef.h>    // offsetof",
        "#include <stdalign.h>  // alignof (C11)",
        "",
    ]
    for inc in includes:
        lines.append(f"#include <{inc}>")
    lines.append("")

    for rec in sorted(records, key=lambda r: r.type_name):
        tn = rec.type_name
        tag = tn.replace(" ", "_")
        lines.append(f"static_assert(sizeof({tn}) == {rec.size}u, "
                     f"\"ABI: sizeof({tn}) changed\");")
        lines.append(f"static_assert(alignof({tn}) == {rec.align}u, "
                     f"\"ABI: alignof({tn}) changed\");")
        for name, off in rec.fields:
            lines.append(f"static_assert(offsetof({tn}, {name}) == {off}u, "
                         f"\"ABI: offsetof({tn}.{name}) changed\");")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate/check ABI layout assertions.")
    parser.add_argument("--include-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--std", default="c++20")
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--isystem", action="append", default=[])
    parser.add_argument("--libclang", default=None)
    parser.add_argument("--check", action="store_true", help="Compare against the committed --output instead of writing it.")
    args = parser.parse_args()

    if args.libclang:
        cindex.Config.set_library_file(args.libclang)

    include_dir: Path = args.include_dir.resolve()
    if not include_dir.is_dir():
        print(f"::error::include directory not found: {include_dir}", file=sys.stderr)
        return 2

    parse_args = (["-x", "c++", f"-std={args.std}", "-I", str(include_dir)]
                  + builtin_include_args(args.clang, args.isystem))
    index = cindex.Index.create()

    records: list[Record] = []
    includes: list[str] = []
    seen: set[str] = set()
    for header in sorted(include_dir.rglob("*.h")):
        include = header.relative_to(include_dir).as_posix()
        new_records = []
        for rec in collect_records(index, header, include, parse_args):
            if rec.type_name not in seen:
                seen.add(rec.type_name)
                new_records.append(rec)
        if new_records:
            includes.append(include)
            records.extend(new_records)

    content = render(records, includes)

    if args.check:
        if not args.output.exists():
            print(f"::error::golden file missing: {args.output}. Run without --check to create it.")
            return 1
        current = args.output.read_text(encoding="utf-8")
        if current != content:
            print("::error::ABI layout assertions are out of date "
                  "(a struct was added, removed, or changed).")
            print(f"Regenerate with: python3 {Path(__file__).name} "
                  f"--include-dir {args.include_dir} --output {args.output}")
            return 1
        print(f"Layout assertions up to date ({len(records)} record(s)).")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} ({len(records)} record(s)).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())