name: reusable-clean-ghcr
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      min-versions-to-keep:
        required: false
        type: number
        default: 3

jobs:
  clean-untagged-images:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.package-name }}
          package-type: container
          min-versions-to-keep: ${{ inputs.min-versions-to-keep }}
          delete-only-untagged-versions: true