name: reusable-docs

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

      output-repository:
        required: true
        type: string

      output-branch:
        required: false
        type: string
        default: cloudflare-pages

      # Generally `dev` or `X.Y.Z`
      deployment-version:
        required: false
        type: string
        default: generated-docs

      erase-existing-output:
        required: false
        type: boolean
        default: false

      additional-dir-to-deploy:
        required: false
        type: string
        default: ""

      deploy-as-hub:
        required: false
        type: boolean
        default: false

    secrets:
      ghcr-token:
        required: true

      push-token:
        required: true

jobs:
  use-build:
    uses: liara-engine/.github/.github/workflows/reusable-build-docs.yml@v0
    with:
      image: ${{ inputs.image }}
      additional-dir-to-deploy: ${{ inputs.additional-dir-to-deploy }}

    secrets:
      ghcr-token: ${{ secrets.ghcr-token }}
      push-token: ${{ secrets.push-token }}

  use-publish:
    needs: use-build
    uses: liara-engine/.github/.github/workflows/reusable-deploy-docs.yml@v0
    with:
      output-repository: ${{ inputs.output-repository }}
      output-branch: ${{ inputs.output-branch }}
      deployment-version: ${{ inputs.deployment-version }}
      erase-existing-output: ${{ inputs.erase-existing-output }}
      deploy-as-hub: ${{ inputs.deploy-as-hub }}

    secrets:
      ghcr-token: ${{ secrets.ghcr-token }}
      push-token: ${{ secrets.push-token }}