name: commitlint

on:
  workflow_call:

jobs:
  commitlint:

    permissions:
      pull-requests: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - run: npm install -g @commitlint/cli @commitlint/config-conventional

      - id: commitlint
        continue-on-error: true
        run: |
          echo "## Commit Lint Results" > comment.md
          echo "" >> comment.md
          echo '```' >> comment.md

          commitlint \
            --from=origin/${{ github.base_ref }} \
            --to=${{ github.sha }} >> comment.md 2>&1

          EXIT_CODE=$?

          echo '```' >> comment.md
          echo "exit_code=$EXIT_CODE" >> $GITHUB_ENV

      - if: env.exit_code == '0'
        run: |
          echo "Everything looks good! No commit message errors found." > comment.md

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: comment.md
          header: 'commitlint'

      - if: env.exit_code != '0'
        run: |
          echo "Commit message errors found. Please check the comment above for details."
          exit 1
