name: reusable-docs

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

      output-repository:
        required: true
        type: string

      output-branch:
        required: false
        type: string
        default: cloudflare-pages

      version:
        required: true
        type: string
        default: ''

      source-repository:
        required: false
        type: string
        default: ''
      source-ref:
        required: false
        type: string
        default: ''
      source-path:
        required: false
        type: string
        default: '.'
      repo:
        required: false
        type: string
        default: ''

      site:
        required: false
        type: string
        default: https://liara-engine.liara-engine-documentation.workers.dev

      skip-api:
        required: false
        type: boolean
        default: false

      update-manifest:
        required: false
        type: string
        default: auto

      docs-shared-ref:
        required: false
        type: string
        default: main

    secrets:
      ghcr-token:
        required: false
      push-token:
        required: true
      read-token:
        required: false

jobs:
  build:
    permissions:
      contents: read
      packages: read
    uses: liara-engine/.github/.github/workflows/reusable-build-docs.yml@v2
    with:
      image: ${{ inputs.image }}
      source-repository: ${{ inputs.source-repository }}
      source-ref: ${{ inputs.source-ref }}
      source-path: ${{ inputs.source-path }}
      repo: ${{ inputs.repo }}
      version: ${{ inputs.version }}
      site: ${{ inputs.site }}
      skip-api: ${{ inputs.skip-api }}
    secrets:
      ghcr-token: ${{ secrets.ghcr-token }}
      read-token: ${{ secrets.read-token }}

  publish:
    needs: build
    permissions:
      contents: read
    uses: liara-engine/.github/.github/workflows/reusable-deploy-docs.yml@v2
    with:
      output-repository: ${{ inputs.output-repository }}
      output-branch: ${{ inputs.output-branch }}
      update-manifest: ${{ inputs.update-manifest }}
      docs-shared-ref: ${{ inputs.docs-shared-ref }}
    secrets:
      ghcr-token: ${{ secrets.ghcr-token }}
      push-token: ${{ secrets.push-token }}
      read-token: ${{ secrets.read-token }}
